#!/bin/sh

case "$1" in
 start|restart|reload)
  ec=0
  /usr/sbin/iptables-restore < /etc/iptables/rules.v4 || ec=1
  /usr/sbin/ip6tables-restore < /etc/iptables/rules.v6 || ec=1
  [ $ec = 0 ] && echo "OK" || echo "FAIL"
  exit $ec
  ;;
 stop)
  # no flush
  exit 0
  ;;
 *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac
